firehose-fire/chess

- .travis.yml
- Gemfile.lock
This reverts commit 901b78c417ebd12bf7cda4809c00ba7416acc703.
> Revert "Setup Travis Cl and authorized it to the project (#4)"

- Gemfile
- Gemfile.lock
- app/assets/javascripts/games.coffee
- app/assets/stylesheets/games.scss
- app/controllers/games_controller.rb
- app/helpers/games_helper.rb
- app/models/game.rb
- config/initializers/simple_form.rb
- config/initializers/simple_form_bootstrap.rb
- config/locales/simple_form.en.yml
- db/migrate/20180901012513_create_games.rb
- lib/templates/erb/scaffold/_form.html.erb
- test/controllers/games_controller_test.rb
- test/fixtures/games.yml
- test/models/game_test.rb
Created GamesController and added new, create and show actions
Created Game model and gave it t.name :string
Added the simple_form gem and integrated with bootstrap
*Have not migrated the database until the .yml file PR is merged.
> Build CRUD, add game model and add simple_form

- config/database.yml
Discovered some issues the .yml file. Added:
username: postgres
password: password
host: localhost
...and commented out the production username and password.
> fix yml file

- spec/factories.rb
Forgot to add this. This will be helpful when creating user test cases in rspec. Creates a user into the database with data and saves it as a placeholder
example use
```
user = FactoryBot.create(:user)
```
> Defined user in Factories for future dummy data testing

- README.md
Change the title of readme to Chess
> Changed title of readme

- app/models/game.rb
When Game.available is called it should find the game that has user_id_white as nil.
I created my own test case to run things but this should technically work. This can be tested when listing available games
> Created a scope for Game model called available

- spec/factories.rb
Here's an example on how to use it when creating a test case
```
game = FactoryBot.create(:game)
```
> Defined a factory to allow creating games.

- app/models/game.rb
- db/schema.rb
I updated the game model to add optional: true to both user white and black.  also removed user_id from the user table.  I thought I did this earlier, but I guess not.
> updated schema changed game model

- app/models/king.rb
- app/models/piece.rb
- spec/factories.rb
- spec/models/king_spec.rb
Went from big, to small, to smaller. Much more concise.
> Valid move king

- app/models/game.rb
- spec/models/pawn_spec.rb
The populate game method now allows us to put the chess pieces on the board in the correct positions and added a limitation for it to only be created once with the after_create action.
> created the populate game method and added only create once limitation

- app/models/piece.rb
- app/models/queen.rb
- spec/models/piece_spec.rb
- spec/models/queen_spec.rb
Used the is_obstructed? method that Cory created into checking if it's a valid_move? as well as if there's an obstruction
> Added Queen valid_move? validation

- app/models/piece.rb
- spec/models/piece_spec.rb
added conditional if statements to better specify which direction diagonal moves
> Add is obstructed

- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
> generated devise views

- app/controllers/games_controller.rb
- app/views/games/show.html.erb
- spec/controllers/games_controller_spec.rb
Fixed a typo in the show page as well. Was missing a / in the div
> Added the forfeit button for the game to the show page

- spec/helpers/pieces_helper_spec.rb
- spec/models/bishop_spec.rb
- spec/models/game_spec.rb
- spec/models/piece_spec.rb
> Calling valid moves tests

- app/controllers/pieces_controller.rb
- app/models/game.rb
- app/models/pawn.rb
- app/models/piece.rb
- db/migrate/20181001183147_add_has_moved_to_piece.rb
- db/schema.rb
- spec/helpers/pieces_helper_spec.rb
- spec/models/bishop_spec.rb
- spec/models/game_spec.rb
- spec/models/pawn_spec.rb
- spec/models/piece_spec.rb
- spec/models/queen_spec.rb
refactored code in pawn model
updated captured?, is_capture_valid and is_occupied in the piece model to only allow for pieces to be searched in the current game instead of all the games.  Pieces.where changed to game.pieces.
update game.rb to put the Queen in the correct location.
added a column to the piece table of has_moved(boolean) to account for if a piece has moved
updated the pieces_controller to call the move_to method which will then call the valid move method
updated is_occupied? to return @piece.present.
after updating everything travis is still not liking 4 things, but much better than the first time.
updated captured? method to use piece_color instead of user_id, helped eliminate some of the run time errors when two different colors were capturing.
updated captured? to show …
> added the ability to call the valid move method

- app/views/games/_board.html.erb
> Updated the _board.html.erb

- app/models/pawn.rb
added horizontal move to valid move for the pawn
> added horizontal move logic for pawn

- app/models/pawn.rb
- app/models/piece.rb
- db/migrate/20181005164101_add_en_passant_to_piece.rb
- db/schema.rb
- spec/models/pawn_spec.rb
created a boolean in the schema to keep track if the pawn is in en_passant state or not
> Added the en_passant method to the pawn

- app/models/game.rb
- app/models/piece.rb
- db/migrate/20181005231953_add_turn_to_games.rb
- db/migrate/20181008000212_change_column_default_to_turn.rb
- db/schema.rb
- spec/factories.rb
- spec/models/bishop_spec.rb
- spec/models/pawn_spec.rb
added turn boolean attribute to games table
added restriction to only allow one color piece to move at a time.
after move is completed will switch turn to other color piece.  
WIP - still need to complete the optional part of indicating whose turn it is
> added turn boolean to db and turn logic
